export const FETCH_TOP_STORY = "FETCH_TOP_STORY";
export const FETCH_SHOW_STORY = "FETCH_SHOW_STORY";
export const FETCH_ASK_STORY = "FETCH_ASK_STORY";
export const FETCH_JOBS_STORY = "FETCH_JOBS_STORY";
export const FETCH_STORY_ERROR = "FETCH_STORY_ERROR";
